const app = document.getElementById('adminApp');
const labels = { news: 'News', events: 'Events', gallery: 'Gallery', documents: 'Documents' };
const icons = { news: 'fa-newspaper', events: 'fa-calendar-days', gallery: 'fa-image', documents: 'fa-file-lines' };
let activeType = 'news'; let editingId = null;
const safe = value => String(value || '').replace(/[&<>'"]/g, char => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[char]));

function login() { app.innerHTML = `<section class="admin-login"><div class="login-card"><div class="login-mark"><i class="fas fa-gem"></i></div><h1>Admin Portal</h1><p>Manage Gold Refinery Hall content.</p><form class="login-form" id="loginForm"><label>Username<input name="username" autocomplete="username" required></label><label>Password<input name="password" type="password" autocomplete="current-password" required></label><button class="admin-btn">Sign in</button></form><p class="login-note">Demo access: <strong>admin</strong> / <strong>goldhall</strong></p><p id="loginError" class="login-error"></p></div></section>`; document.getElementById('loginForm').onsubmit = e => { e.preventDefault(); const form = new FormData(e.target); if (form.get('username') === 'admin' && form.get('password') === 'goldhall') { sessionStorage.setItem('goldHallAdmin', 'true'); dashboard(); } else document.getElementById('loginError').textContent = 'Incorrect username or password.'; }; }
function dashboard() { app.innerHTML = `<div class="admin-shell"><aside class="admin-side"><div class="admin-brand"><h1>Gold Refinery Hall</h1><p>Content Management</p></div><nav class="admin-nav">${Object.keys(labels).map(type => `<button data-type="${type}" class="${type === activeType ? 'active' : ''}"><i class="fas ${icons[type]}"></i>${labels[type]}</button>`).join('')}<button id="logout"><i class="fas fa-right-from-bracket"></i>Sign out</button></nav></aside><main class="admin-main"><div class="admin-top"><div><h2>Manage ${labels[activeType]}</h2><p>Add, update, publish or remove public content.</p></div><button class="admin-btn secondary" id="resetContent">Restore sample content</button></div><div class="admin-grid"><section class="panel"><h3 id="formTitle">Add ${labels[activeType].slice(0,-1)}</h3><form class="editor-form" id="editorForm"><label>Title<input name="title" required></label><label>Description<textarea name="text" required></textarea></label><label>${activeType === 'gallery' ? 'Image URL' : activeType === 'events' ? 'Date and location' : 'Category or label'}<input name="meta"></label><label><input name="published" type="checkbox" checked> Publish on the website</label><button class="admin-btn">Save ${labels[activeType].slice(0,-1)}</button><button type="button" class="admin-btn secondary" id="cancelEdit" hidden>Cancel edit</button></form></section><section class="panel"><h3>Saved ${labels[activeType]}</h3><div id="contentList" class="content-list"></div></section></div></main></div>`; document.querySelectorAll('[data-type]').forEach(button => button.onclick = () => { activeType = button.dataset.type; editingId = null; dashboard(); }); document.getElementById('logout').onclick = () => { sessionStorage.removeItem('goldHallAdmin'); login(); }; document.getElementById('resetContent').onclick = () => { if (confirm('Restore the original sample content?')) { GoldHallStore.reset(); dashboard(); } }; document.getElementById('editorForm').onsubmit = save; document.getElementById('cancelEdit').onclick = () => { editingId = null; dashboard(); }; renderList(); }
function renderList() { const list = document.getElementById('contentList'); const items = GoldHallStore.get(activeType); list.innerHTML = items.length ? items.map(item => `<article class="content-row"><div><h4>${safe(item.title)}</h4><p>${safe(item.meta)}</p><span class="status ${item.published ? '' : 'draft'}">${item.published ? 'Published' : 'Draft'}</span></div><div class="row-actions"><button title="Edit" data-edit="${item.id}"><i class="fas fa-pen"></i></button><button title="Delete" data-delete="${item.id}"><i class="fas fa-trash"></i></button></div></article>`).join('') : '<p>No content yet. Add your first item using the form.</p>'; list.querySelectorAll('[data-edit]').forEach(button => button.onclick = () => edit(button.dataset.edit)); list.querySelectorAll('[data-delete]').forEach(button => button.onclick = () => { if (confirm('Delete this item?')) { GoldHallStore.remove(activeType, button.dataset.delete); dashboard(); } }); }
function edit(id) { const item = GoldHallStore.get(activeType).find(entry => entry.id === id); editingId = id; const form = document.getElementById('editorForm'); form.title.value = item.title; form.text.value = item.text; form.meta.value = item.meta; form.published.checked = item.published; document.getElementById('formTitle').textContent = `Edit ${labels[activeType].slice(0,-1)}`; document.getElementById('cancelEdit').hidden = false; form.scrollIntoView({ behavior: 'smooth' }); }
function save(event) { event.preventDefault(); const form = new FormData(event.target); GoldHallStore.save(activeType, { id: editingId || `${activeType}-${Date.now()}`, title: form.get('title').trim(), text: form.get('text').trim(), meta: form.get('meta').trim(), published: form.get('published') === 'on' }); editingId = null; dashboard(); }
sessionStorage.getItem('goldHallAdmin') === 'true' ? dashboard() : login();
